services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: manage_petro
      MYSQL_USER: mp
      MYSQL_PASSWORD: mp
      MYSQL_ROOT_PASSWORD: root
    ports: ["3307:3306"]
    volumes: [ "mysql_data:/var/lib/mysql" ]
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: manage_petro
      DB_USERNAME: mp
      DB_PASSWORD: mp
      REDIS_HOST: redis
      VITE_DEV_SERVER_URL: http://node:5173
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  node:
    image: node:20-alpine
    working_dir: /var/www/html
    command: sh -c "tail -f /dev/null"
    volumes:
      - ./:/var/www/html
    ports: ["5173:5173"]
    depends_on: [ php ]

  nginx:
    image: nginx:alpine
    ports: ["8000:80"]
    volumes:
      - ./public:/var/www/html/public:ro
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [ php, node ]

volumes:
  mysql_data:
